version: "version"
services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/drug-order-app"
    ports:
      - 3000:3000
  mongodb:
    image: mongo:5.0.7
    ports:
      - 37107:27107
    volumes:
      - ./data:/data/db
