                ### CUSTOMER ###
### CREATE A NEW CUSTOMER
POST http://localhost:3000/customers/login HTTP/1.1
content-type: application/json

{"email": "test@test.com","password":"123456"}

###

POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"name":"Erkan", "email": "test@test.com", "password":"123456", "location": "Izmir", "age": 33}

### GET A CUSTOMER

GET http://localhost:3000/customers/626427e86d758fefaf2f81ec HTTP/1.1

### DELETE A CUSTOMER

DELETE http://localhost:3000/customers/6297534c96b8cbfe1257d075 HTTP/1.1

### CREATE A NEW ORDER

POST http://localhost:3000/customers/62711415ed1b686ff77c9285/orders HTTP/1.1
content-type: application/json

{"pharmacyId":"627116be308c7d575470503f", "drugId":"627116c5308c7d5754705041"}

                ### PHARMACY ###
###CREATE A PHARMACY

POST https://backend-4m7nspnvoa-ew.a.run.app/pharmacies HTTP/1.1
content-type: application/json

{"name":"Drug Store", "location": "Mecidiyekoy"}

### ADD A DRUG TO DRUGLIST

POST http://localhost:3000/pharmacies/6298c2cc448ae475e6c9943b/druglist HTTP/1.1
content-type: application/json

{"drugId":"62711733ea78c92e9299ff65"}

                ### DRUGS ###
### CREATE A DRUG

POST https://backend-4m7nspnvoa-ew.a.run.app/drugs/ HTTP/1.1
content-type: application/json

{"name":"Arvales"}

### UPDATE A DRUG'S NAME

PATCH http://localhost:3000/drugs/6264213ad14f74a35c8e494b HTTP/1.1
content-type: application/json

{"name": "Newer Drug"}

### UPDATE A PHARMACY'S NAME

PATCH http://localhost:3000/pharmacies/6298c2cc448ae475e6c9943b HTTP/1.1
content-type: application/json

{"name": "Drug Store"}




